### ISSUE TITLE
Add omnios r151052

### ISSUE THREAD

**Issue by sunshowers** [vmactions/omnios-builder#1]
Hi there, thanks for maintaining vmactions!

I was wondering if you could also add OmniOS r151052 -- it was released a few days ago and adds some new APIs that I wanted to use in tests. Thanks!

**Comment by neilpang** [comment]
try with the latest release.
https://github.com/vmactions/omnios-vm/releases

**Comment by sunshowers** [comment]
Thank you so much! I'll try it out ASAP.
